name: Build V8

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python pkg-config libnss3-dev libgconf-2-4
        # Add any other dependencies needed for V8 compilation

    - name: Clone V8 repository
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH="$PWD/depot_tools:$PATH"

    - name: Checkout V8 branch
      run: |
        cd depot_tools
        fetch v8
        cd v8
        gclient sync -r remotes/branch-heads/8.9

    - name: Sync V8
      run: |
        gclient sync

    - name: Install build dependencies
      run: |
        ./build/install-build-deps.sh

    - name: Generate build files
      run: |
        gn gen out.gn/linux_64/release --args="target_cpu=\"x64\" v8_target_cpu=\"x64\" is_debug=false is_clang=true use_sysroot=false v8_monolithic=true is_component_build=false use_custom_libcxx=false treat_warnings_as_errors=false v8_use_external_startup_data=false v8_static_library=true"

    - name: Build V8
      run: |
        ninja -C out.gn/linux_64/release v8_monolith
